CREATE DATABASE IF NOT EXISTS jay_dee_bank;
USE jay_dee_bank;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(30) NOT NULL DEFAULT '',
  gender VARCHAR(20) NOT NULL DEFAULT '',
  dob VARCHAR(30) NOT NULL DEFAULT '',
  address VARCHAR(255) NOT NULL DEFAULT '',
  account_number VARCHAR(32) NOT NULL UNIQUE,
  balance DOUBLE NOT NULL DEFAULT 0,
  password VARCHAR(255) NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  transactions_json LONGTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  category VARCHAR(30) NOT NULL,
  risk_level VARCHAR(20) NOT NULL DEFAULT 'moderate',
  min_age INT NOT NULL DEFAULT 18,
  max_age INT NOT NULL DEFAULT 100,
  min_balance DOUBLE NOT NULL DEFAULT 0,
  summary TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recommendation_feedback (
  id INT AUTO_INCREMENT PRIMARY KEY,
  account_number VARCHAR(32) NOT NULL,
  product_id INT NOT NULL,
  action VARCHAR(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (account_number) REFERENCES users(account_number),
  FOREIGN KEY (product_id) REFERENCES products(id)
);
